// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingWithCalvin.WebcamStudio
{
    internal sealed partial class Vsix
    {
        public const string Id = "VS-WebcamStudio";
        public const string Name = "Webcam Studio";
        public const string Description = @"This extension allows you to embed your webcam into a tool window within Visual Studio. Useful if you like to live stream and want a completely integrated environment!";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Coding With Calvin";
        public const string Tags = "webcam,cam,livestream";
    }
}
